# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cjosue <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/05 12:53:50 by cjosue            #+#    #+#              #
#    Updated: 2019/09/05 18:13:47 by cjosue           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME_PROGRAM  = strlen
NAME_C = ft_strlen.c

all:
		@gcc -Wall -Wextra -Werror main_$(NAME_PROGRAM).c \
		/Users/cjosue/Desktop/Libft/$(NAME_C) \
		-I /Users/cjosue/Desktop/Libft/  \
		-o $(NAME_PROGRAM)
