# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cjosue <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/05 12:53:50 by cjosue            #+#    #+#              #
#    Updated: 2019/09/07 19:05:20 by cjosue           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME_PROGRAM  = isalpha
NAME_C = ft_isalpha.c

all:
		@gcc -Wall -Wextra -Werror main_$(NAME_PROGRAM).c \
		-L/Users/cjosue/Desktop/Libft/ -lft \
		-I /Users/cjosue/Desktop/Libft/ \
		-o $(NAME_PROGRAM)
