# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cjosue <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/05 12:53:50 by cjosue            #+#    #+#              #
#    Updated: 2019/09/11 18:10:38 by cjosue           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME_PROGRAM  = get_next_line
NAME_C = get_next_line.c

all:
		@gcc -Wall -Wextra -Werror main_$(NAME_PROGRAM).c $(NAME_C)\
		-L/Users/cjosue/Desktop/My_Git/get_next_line/libft  -lft \
		-I /Users/cjosue/Desktop/My_Git/get_next_line/libft \
		-o $(NAME_PROGRAM)
