# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cjosue <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/05 12:53:50 by cjosue            #+#    #+#              #
#    Updated: 2019/09/13 10:01:33 by cjosue           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME_PROGRAM  = atoi
NAME_C = ft_atoi.c

all:
		@gcc -Wall -Wextra -Werror main_$(NAME_PROGRAM).c \
		-L/Users/cjosue/Desktop/Libf_My_Git/Libft -lft \
		-I /Users/cjosue/Desktop/Libf_My_Git/Libft \
		-o $(NAME_PROGRAM)
